### ISSUE TITLE
End the session automatically

### ISSUE THREAD

**Issue by GiggleLiu** [yeahjack/chatgpt_zulip_bot#16]
Some users are confused by the 3k token limit and do not know how to end the conversation.

**Comment by yeahjack** [comment]
Actually, by `/help`, you could get the instructions you could use. `/end` could end the conversation.

**Comment by GiggleLiu** [comment]
What can be the potential issue of ending session automatically? There is no other choice except ending session when token limit is reached.

**Comment by yeahjack** [comment]
I think I could implement this during the weekend.

**Comment by GiggleLiu** [comment]
Thanks, that would be very helpful! I am not sure whether ending the conversation is the most urgent one, since the error message is quite clear. What about
1. implement a new command `/retry` to end conversation and try again, because it is annoying to copy-paste the text after the rate limit is reached.
2. improve the error message to make it even more clear.

```
Please type `/retry` to end the conversation and try again or shorten your prompt,
since the Open-API token limit has reached.
```

## Contextual information
![image](https://github.com/yeahjack/chatgpt_zulip_bot/assets/6257240/4b14d7e9-7c50-4559-81ad-cbb7b373aa32)

Claire said there will be 100-200 bachelers joining our platform during this summer. So it would be great if we can put some effort in improving the using experience.

**Comment by yeahjack** [comment]
May I have a look at the `image.png`

**Comment by yeahjack** [comment]
Fix in https://github.com/yeahjack/chatgpt_zulip_bot/commit/f82c5bc90c16c22db26e285cad16d2a35a9c4c94 .
