### ISSUE TITLE
[Bug] The bot's status cannot be set to `away` when it's offline or not running.

### ISSUE THREAD

**Issue by GiggleLiu** [yeahjack/chatgpt_zulip_bot#6]
The bot's status cannot be set to `away` when it's offline or not running.

*NOTE: This is moved from the `README.md`.*

**Comment by yeahjack** [comment]
Yes, I am afraid this is related to the Zulip API. Will look into it this weekend with another interesting feature: output by stream like real ChatGPT!

**Comment by yeahjack** [comment]
I will close this issue, as just letting the bot run all the time could avoid this demand. Some libraries, such as `supervisorctl` could help.
